### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by ResqDiver1317** [JaredScar/BadgerStaffPanel#1]
So looking over this, and I could be 100% wrong but here goes, this looks like an well updated version of the old CADOJRP FiveM Admin Panel (which is what we are currently running) and appears to have some nice new features, mainly what caught my eye was Discord Integration). 

Would it be possible to import current data from the CADOJRP admin panel into this database so we could retain all of the previous actions issued as well as playtimes if we change?

I see the config has spots for 4 different staff roles but I was wondering if it will allow for additional in the same way the CADOJRP panel does? We technically have 7 diff staff ranks and 5 diff permission sets (T-Mod, Mod, Admin, SR Admin each have their own progressive sets of power) and Head Admin, Co-Director, and Director all have the same powers. Would I be able to setup all 7 roles so I don't need multiple roles on our senior staff to ensure Co-Directors and Directors have the correct level of access to the panel?

I love the fact this works on Discord Roles as we have been moving most of our permissions for various aspects in game to discord permissions thanks to several other of your amazing resources and this would be one more thing we could change over, I just don't want to lose all of our current data by doing so.

**Comment by JaredScar** [comment]
You could probably import the data if you altered some of the tables to match their layout, then you'd need to change my panel's code probably as well. The config supports multiple roles, so long as the format is followed for adding more.

**Comment by JaredScar** [comment]
Closing this considering it's been about 2 weeks with no response.
