### ISSUE TITLE
Security vulnerability through unused net events

### ISSUE THREAD

**Issue by glitchdetector** [JaredScar/BadgerStaffPanel#2]
https://github.com/JaredScar/BadgerStaffPanel/blob/2285e657ea03651b805af2b00ccd3b20d85e13cb/BadgerStaffPanel-Script/server.lua#L1-L5

The script doesn't rely on a client side, and these events are only called locally on the server (not through net), making the net event registration redundant and opens up for """malicious""" stuff.
The event handlers also do not contain any checks for ACE permissions, allowing any client to potentially kick and/or ban players, and add details to the database.

Removing the net event registration should resolve this.

**Comment by JaredScar** [comment]
Can you make a pull request for this if possible?
