### ISSUE TITLE
Getting native error when trying to connect to server w/ this resource

### ISSUE THREAD

**Issue by realneonium** [JaredScar/BadgerStaffPanel#4]
i am constantly getting the same native error when i am joining my server while badgerstaffpanel-script is started, i have no clue whats going on
i have tried reinstalling the default resource with no success
the website that i set the panel up on seems to work completely fine, just seems to be a problem with the resource (?)
i dont believe im getting any errors through mysql-async either "[mysql-async] [SUCCESS] Database server connection established."
![image](https://user-images.githubusercontent.com/73816044/112379096-d1046100-8c8b-11eb-98b5-ab1a3546a0cc.png)
as soon as it tries to load BadgerStaffPanel-Script it sends me that error in console and in fivem it stays on "BadgerStaffPanel-Script: Deferring connection" and then eventually just fails to handshake
all i was really able to gather was that the native points me here https://docs.fivem.net/natives/?_0x406B4B20
it would be nice if i could just get pointed in the direction of what could be causing the issue

**Comment by JaredScar** [comment]
This is an issue with setup, not the project itself...
